export const mapsConstants = {
    USER_LOCATION: 'USER_LOCATION',
    USER_ADDRESS: 'USER_ADDRESS',
    OBTENER_SEDES: 'OBTENER_SEDES',
    EMPRESA_SELECCIONADA: 'EMPRESA_SELECCIONADA',
    VER_INFO_EMPRESA: 'VER_INFO_EMPRESA',
    VER_MENU_BUSQUEDA: 'VER_MENU_BUSQUEDA',
    VER_INICIO_FACE: 'VER_INICIO_FACE',
    GUARDAR_MAPA: 'GUARDAR_MAPA',
    GUARDAR_LAYER_SELECCIONADO: 'GUARDAR_LAYER_SELECCIONADO',
    GUARDAR_POSICION_CENTRAL: 'GUARDAR_POSICION_CENTRAL',
    OBTENER_MUNICIPIO: 'OBTENER_MUNICIPIO',
    OBTENER_SEDE: 'OBTENER_SEDE'
    
}