export const subcategoriaConstants = {
    OBTENER_SUBCAT: 'OBTENER_SUBCAT',
    CARGAR_EDITAR_SUBCATEGORIA: 'CARGAR_EDITAR_SUBCATEGORIA',
    MOSTRAR_CREATE_SUBCATEGORIA: 'MOSTRAR_CREATE_SUBCATEGORIA',
    MOSTRAR_EDITAR_SUBCATEGORIA: 'MOSTRAR_EDITAR_SUBCATEGORIA',
    CREAR_SUBCATEGORIA: 'CREAR_SUBCATEGORIA',
    EDITAR_SUBCATEGORIA: 'EDITAR_SUBCATEGORIA',
    SUBCATE_SEL: 'SUBCATE_SEL',
    OBTENER_SUB_CAT: 'OBTENER_SUB_CAT',
    CREAR_CATE_SUBCATEGORIA: 'CREAR_CATE_SUBCATEGORIA',
    SELECCIONAR_CATSUBCA: 'SELECCIONAR_CATSUBCA',
    ELIMINAR_CATE_SUBCATEGORIA: 'ELIMINAR_CATE_SUBCATEGORIA',
    ELIMINAR_SUBCATEGORIA: 'ELIMINAR_SUBCATEGORIA'
};