export const empresaConstants = {

    CARGAR_EMPRESAS: 'CARGAR_EMPRESAS',

    CARGAR_CREATE_EMPRESA: 'CARGAR_CREATE_EMPRESA',
    CARGAR_EDITAR_EMPRESA: 'CARGAR_EDITAR_EMPRESA',
    MOSTRAR_CREATE_EMPRESA: 'MOSTRAR_CREATE_EMPRESA',
    MOSTRAR_EDITAR_EMPRESA: 'MOSTRAR_EDITAR_EMPRESA',
    CREAR_EMPRESA: 'CREAR_EMPRESA',
    EDITAR_EMPRESA: 'EDITAR_EMPRESA',
    EMPRESA_SELECCIONADA: 'EMPRESA_SELECCIONADA'

};