export const categoriaConstants = {
    OBTENER_CAT: 'OBTENER_CAT',
    CARGAR_EDITAR_CATEGORIA: 'CARGAR_EDITAR_CATEGORIA',
    MOSTRAR_CREATE_CATEGORIA: 'MOSTRAR_CREATE_CATEGORIA',
    MOSTRAR_EDITAR_CATEGORIA: 'MOSTRAR_EDITAR_CATEGORIA',
    CREAR_CATEGORIA: 'CREAR_CATEGORIA',
    EDITAR_CATEGORIA: 'EDITAR_CATEGORIA',
    SELECCIONAR_CATEGORIA: 'SELECCIONAR_CATEGORIA',
    ELIMINAR_CATEGORIA: 'ELIMINAR_CATEGORIA'
};