export const municipioConstants = {
    OBTENER_MUNICIPIOS: 'OBTENER_MUNICIPIOS',
    CARGAR_EDITAR_MUNICIPIO: 'CARGAR_EDITAR_MUNICIPIO',
    MOSTRAR_CREATE_MUNICIPIO: 'MOSTRAR_CREATE_MUNICIPIO',
    MOSTRAR_EDITAR_MUNICIPIO: 'MOSTRAR_EDITAR_MUNICIPIO',
    CREAR_MUNICIPIO: 'CREAR_MUNICIPIO',
    EDITAR_MUNICIPIO: 'EDITAR_MUNICIPIO',
    SELECCIONAR_MUNICIPIO: 'SELECCIONAR_MUNICIPIO'
};