export const menuFiltroConstants = {
    OBTENER_CATEGORIAS: 'OBTENER_CATEGORIAS',
    ASIGNAR_ITEM_ACTIVE: 'ASIGNAR_ITEM_ACTIVE',
    VER_FILTRO_FLOTANTE: 'VER_FILTRO_FLOTANTE',
    OBTENER_SUBCATEGORIAS: 'OBTENER_SUBCATEGORIAS',
    AGREGAR_SUBCATEGORIAS_FILTRO: 'AGREGAR_SUBCATEGORIAS_FILTRO',
    SELECIONAR_MUNICIPIO: 'SELECIONAR_MUNICIPIO',
    CAMBIAR_ZOOM_MAP: 'CAMBIAR_ZOOM_MAP',
    SELECIONAR_CATEGORIA: 'SELECIONAR_CATEGORIA',
    POSICION_CENTRAL_MAPA: 'POSICION_CENTRAL_MAPA',
    NOMBRE_MUNICIPIO_SELECCIONADO: 'NOMBRE_MUNICIPIO_SELECCIONADO',

    
}