export const sedeConstants = {
    CARGAR_CREATE_SEDE: 'CARGAR_CREATE_SEDE',
    CARGAR_EDITAR_SEDE: 'CARGAR_EDITAR_SEDE',
    MOSTRAR_CREATE_SEDE: 'MOSTRAR_CREATE_SEDE',
    MOSTRAR_EDITAR_SEDE: 'MOSTRAR_EDITAR_SEDE',
    CREAR_SEDE: 'CREAR_SEDE',
    EDITAR_SEDE: 'EDITAR_SEDE',
    SEDE_SELECCIONADA: 'SEDE_SELECCIONADA',
    CARGAR_CREAR_SEDE: 'CARGAR_CREAR_SEDE',

};