export const usuarioConstants = {
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',
    OBTENER_USUARIOS: 'OBTENER_USUARIOS',
    CARGAR_CREATE_USER: 'CARGAR_CREATE_USER',
    CARGAR_EDITAR_USER: 'CARGAR_EDITAR_USER',
    MOSTRAR_CREATE_USER: 'MOSTRAR_CREATE_USER',
    MOSTRAR_EDITAR_USER: 'MOSTRAR_EDITAR_USER',
    CREAR_USUARIO: 'CREAR_USUARIO',
    EDITAR_USUARIO: 'EDITAR_USUARIO',
    SELECCIONAR_USUARIO: 'SELECCIONAR_USUARIO',
    ENVIAR_CONTACTO: 'ENVIAR_CONTACTO',
};